project:
  type: book
  output-dir: docs

book:
  title: "Illumina metagenomic data analysis"
  author: "Luc van Zon"
  search: TRUE
  date: "03/13/2025"
  chapters:
    - index.qmd
    - chapters/IMAM-02-quick_start.qmd
    - chapters/IMAM-03-quality_control.qmd
    - chapters/IMAM-04-assembly.qmd
    - chapters/IMAM-05-annotation.qmd
    - chapters/IMAM-06-parse_annotation.qmd

toc: true
number-sections: true
number-depth: 3

format:
  html:
    theme:
      light: flatly
      dark: darkly

