channels:
  - conda-forge
  - bioconda
dependencies:
  # Core
  - conda-forge::python=3.12

  # Other tools
  - conda-forge::libdeflate=1.22
  - bioconda::htslib=1.22.1
  - bioconda::snakemake=9.9.0
  - bioconda::diamond=2.1.13
  - bioconda::spades=4.2.0
  - bioconda::cd-hit-auxtools=4.8.1
  - bioconda::fastp=1.0.1
  - bioconda::bwa=0.7.19
  - bioconda::seqkit=2.10.0
  - conda-forge::biopython=1.85
  - bioconda::samtools=1.22.1
  - conda-forge::rsync=3.4.1
name: imam